# Generated by Django 5.1.7 on 2025-03-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_otp_expiry'),
        ('core', '0002_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dgital_product',
            fields=[
                ('digital_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.TextField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('review_text', models.TextField()),
                ('createdat', models.DateField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
    ]
