# Generated by Django 5.1.7 on 2025-03-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dgital_product_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='createdat',
        ),
    ]
