# Generated by Django 5.1.7 on 2025-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_created_at_product_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_attributes',
            old_name='values',
            new_name='value',
        ),
    ]
