# Generated by Django 5.1.7 on 2025-03-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeOption',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_category', models.CharField(max_length=200)),
                ('size_name', models.CharField(max_length=200)),
                ('sotck_in_qnt', models.IntegerField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productvariants')),
            ],
        ),
    ]
