# Generated by Django 5.1.7 on 2025-03-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productvariants_attribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sub_category',
            new_name='parent_category',
        ),
    ]
