# Generated by Django 5.1.7 on 2025-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_sub_category_categories_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
