# Generated by Django 5.1.7 on 2025-03-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_orderitem_payment_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cratedat',
            new_name='createdat',
        ),
    ]
